import {createClient} from 'npm:@supabase/supabase-js@2'
const URL=Deno.env.get('SUPABASE_URL')!,KEY=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,PASS=Deno.env.get('ADMIN_PASSWORD')!,MAINT=Deno.env.get('CRM_MAINTENANCE_SECRET')!
const db=createClient(URL,KEY,{auth:{persistSession:false}}),origin='https://m2-energy-crm.netlify.app'
const headers={'content-type':'application/json','access-control-allow-origin':origin,'access-control-allow-headers':'content-type,x-admin-password','access-control-allow-methods':'GET,PATCH,POST,OPTIONS'}
const reply=(data:unknown,status=200)=>new Response(JSON.stringify(data),{status,headers})
const price:Record<string,number>={solo:49,team:149,agency:349,solo_annual:39,team_annual:119,agency_annual:279}
async function invoke(slug:string,body={}){const r=await fetch(`${URL}/functions/v1/${slug}`,{method:'POST',headers:{'content-type':'application/json','x-crm-maintenance-secret':MAINT},body:JSON.stringify(body)});return await r.json()}
Deno.serve(async req=>{
  if(req.method==='OPTIONS')return new Response('ok',{headers});if(!PASS||req.headers.get('x-admin-password')!==PASS)return reply({error:'Unauthorized'},401)
  if(req.method==='PATCH'||req.method==='POST'){const body=await req.json().catch(()=>({}));if(body.action==='support_status'){if(!['open','in_progress','resolved'].includes(body.status))return reply({error:'Invalid status'},400);const {error}=await db.from('crm_support_requests').update({status:body.status,updated_at:new Date().toISOString()}).eq('id',body.id);return error?reply({error:error.message},500):reply({ok:true})}if(body.action==='run_lifecycle')return reply(await invoke('send-lifecycle'));if(body.action==='run_backup')return reply(await invoke('crm-maintenance',{action:'backup'}));return reply({error:'Unknown action'},400)}
  const {data:accounts,error}=await db.from('master_accounts').select('name,email,plan_key,plan_status,plan_expires_at,stripe_customer_id,stripe_subscription_id,team_id,created_at,activated_at').order('created_at',{ascending:false});if(error)return reply({error:error.message},500)
  const rows=await Promise.all((accounts||[]).map(async a=>{const team=String(a.team_id||'');const [leads,agents,activation,support,maintenance]=await Promise.all([
    db.from('leads').select('*',{count:'exact',head:true}).eq('team_id',team).is('deleted_at',null),db.from('crm_team_members').select('*',{count:'exact',head:true}).eq('team_id',team).eq('role','agent'),db.from('crm_activation_events').select('milestone').eq('team_id',team),db.from('crm_support_requests').select('*',{count:'exact',head:true}).eq('team_id',team).neq('status','resolved'),db.from('maintenance_runs').select('job_type,status,started_at,error').eq('team_id',team).order('started_at',{ascending:false}).limit(2)
  ]);const milestones=new Set((activation.data||[]).map(x=>x.milestone));return {...a,team_id:team,leads:leads.count||0,agents:agents.count||0,activation_pct:Math.round(milestones.size/6*100),open_support:support.count||0,maintenance:maintenance.data||[]}}))
  const [{data:support},{data:health},{data:webhooks}]=await Promise.all([db.from('crm_support_requests').select('*').order('created_at',{ascending:false}).limit(100),db.from('crm_health_events').select('team_id,level,category,message,created_at').order('created_at',{ascending:false}).limit(100),db.from('stripe_webhook_events').select('event_id,event_type,status,error,received_at,processed_at').order('received_at',{ascending:false}).limit(100)])
  const active=rows.filter(x=>['active','trial','trialing'].includes(x.plan_status)),mrr=active.filter(x=>x.plan_status==='active').reduce((s,x)=>s+(price[x.plan_key]||0),0)
  return reply({total:rows.length,active:active.length,mrr,accounts:rows,support:support||[],health:health||[],webhooks:webhooks||[],open_support:(support||[]).filter(x=>x.status!=='resolved').length,webhook_failures:(webhooks||[]).filter(x=>x.status==='failed').length})
})
